# Programming for Chemistry 2025/2026 @ UniMI

![logo](logo_small.png "Logo")

## Lecture 19: Problems in Python

I apologize I couldn't prepare the lecture on *sound synthesis* because I've got flu during the weekend.

Instead, today I'll propose you two or three small Python problems to exercise *lists, strings, dictionaries* and *recursion*. In addition to that, the problems are best solved using **NumPy** arrays and visualized with **Matplotlib**.

# 1. Loops, lists, etc...

## 1.1 Print icecream flavors
Given a list of icecream flavors, print all possible **unique** combinations of two- and three-flavors incluing always **Pistacchio**.

![gelato](bud_spencer.jpeg "Gelato")

In [ ]:
FLAVORS = ["Banana", "Chocolate", "Lemon", "Pistacchio", "Raspberry", "Strawberry", "Vanilla"]

In [ ]:
# print two flavors
...

In [ ]:
# print three flavors
...

## 2.2 Perfect deck shuffle
Simulate a perfect suffle of a deck of cards. A perfect shuffle of a deck of card is splitting a deck of cards into equal halves, and perfectly interleaving them.

![carte](terence_hill.jpeg "Carte")

Perfectly shuffling `[1, 2, 3, 4, 5, 6]` gives `[1, 4, 2, 5, 3, 6]`. We consider that a deck of cards has an even number of cards.

Try to write a function that works by returning a new list (*out-of-place*). **Optionally** write a function that works *in-place*, i.e. without creating a new list.

Did you know that if you perfect shuffle 10 times a deck of 1024 cards, the deck returns to its initial state ? It's probably a good way to test your implementation.

In [ ]:
# out-of-place version
def perfect_shuffle(deck):
    n = len(deck)
    if n % 2 != 0:
        raise ValueError("Deck must have even length for perfect shuffle")
    
    ...
 
    return new_deck

In [ ]:
def perfect_shuffle_inplace(deck):
    n = len(deck)
    if n % 2 != 0:
        raise ValueError("Deck must have even length for perfect shuffle")
    
    # For out-shuffle, final positions follow pattern:
    # position i goes to position (2*i) % (n-1) for i in [1, n-2]
    # position 0 stays at 0, position n-1 stays at n-1
    
    # Track which positions have been moved using a visited array
    visited = [False] * n
    visited[0] = visited[n-1] = True  # Top and bottom stay in place
    
    ...

In [ ]:
# tests 1
ncards = 10
deck = list(range(ncards))
print("starting deck:", deck)

deck = perfect_shuffle(deck)
print("final deck   :", deck)

In [ ]:
# tests 2
ncards = 1024
deck = list(range(ncards))

starting_deck = deck.copy()

for i in range(10):
    deck = perfect_shuffle(deck)
    #perfect_shuffle_inplace(deck)

print(starting_deck == deck)

## 2.3 Draw a Christmas tree
Draw a Christmas tree of size `n` according to the following pattern:
* for `n==1` draw a triangle of 4 lines
* for `n==2` draw a traingle of 4 lines, then a triangle of 5 lines
* for `n==3` the above plus a triangle of 6-lines

E.g.:
![trees](trees.png "Trees")


In [ ]:
def print_tree(n):
    assert n > 0
    ...

In [ ]:
print_tree(4)

# 2. Abelian sandpiles
**Simulate gravity applied to a sandpile.**

![sandpile](sandpile.jpeg "Sandpile")

Write a function `apply_gravity()` that given a 2D numpy array representing sand will *apply gravity* on it (and returns nothing):
* Each element of the array is an integer representing the height of the sandpile
* Any *pile* that has 4 or more sand particles on it collapses, resulting in four particles being subtracted from the pile and distributed among its neighbors

Write also functions to:
* initialize the 2d sandpile of size (width x height) with random numbers lesser than 4
* initialize the 2d sandpile of size (width x height) with zeros
* add one or more grains of sand at a specified position
* visualize the 2d array from above using `plt.imshow()`

### Examples
1. Create a 25x25 initial empty sandpile and add 5000 grains in the middle.
2. Create a 100x100 random matrix and add 500 grains of sand at 10 random positions.

### Hints
1. The code will be quite slow when using loops on a NumPy array. Try to use `np.all()`/`np.any()` and `np.where()` find quickly the piles which are larger or equal than 4.
2. To to this you have to explore what `np.where(sandpile >= 4)` returns.
3. If you want, you can write a *class*.

In [ ]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import random

In [ ]:
def sandpile_random(width, height):
    ...
    return sandpile

def sandpile_empty(width, height):
    ...
    return sandpile


def add_grains(sandpile, i, j, ngrains=1):
    ...


def show_sandpile(sandpile):
    fig = plt.figure(figsize=(4,4.5))
    plt.imshow(sandpile, cmap='Blues')
    plt.colorbar()
    plt.show()


In [ ]:
def simulate_gravity(sandpile):
    ...


In [ ]:
def simulate_gravity_fast(sandpile):
    ...

This test is to check your implementation. The result should be:
```python
[[0 0 1 0 0]
 [0 2 1 2 0]
 [1 1 0 1 1]
 [0 2 1 2 0]
 [0 0 1 0 0]]
```

In [ ]:
# test 0
sandpile = sandpile_empty(5, 5)
add_grains(sandpile, 2, 2, 16)
simulate_gravity(sandpile)
print(sandpile)

In [ ]:
# test 1
sandpile = sandpile_empty(25, 25)
add_grains(sandpile, 12, 12, 5000)
simulate_gravity(sandpile)
#simulate_gravity_fast(sandpile)

show_sandpile(sandpile)

In [ ]:
# test 2
W, H = 100, 100

sandpile = sandpile_random(W, H)
for l in range(10):
    i = random.randint(0, W-1)
    j = random.randint(0, H-1)
    add_grains(sandpile, i, j, ngrains=500)
    simulate_gravity(sandpile)

show_sandpile(sandpile)